// Curated per-destination data. Prices are typical USD medians for a mid-range
// traveller (street food / casual meal, coffee, 3km taxi, mid-range hotel night,
// headline attraction). Sources: public cost-of-living datasets, tourism boards;
// treat as ballpark, the fair-price checker says so on screen.

export const PLACE_DATA = {
  iceland: {
    key: "iceland", name: "Blue Lagoon", country: "Iceland", flag: "🇮🇸",
    lat: 63.88, lng: -22.45, tz: "Atlantic/Reykjavik",
    currency: "ISK (~140 per $1)",
    bestView: "The north edge of the lagoon at sunset, steam drifting over the water with Mt. Þorbjörn behind",
    bestMonths: "June to August for light, February to April for northern lights",
    crowd: "Busy 11:00 to 16:00. Book the first or last slot of the day for near-empty water",
    kid: "Kids 8+ love the floating mask bar and the algae mask ritual. Water is 38°C, safe for long soaks",
    adventure: ["Lava-field hiking at Reykjanes", "Snorkelling the Silfra fissure (45 min away)", "Golden Circle drive"],
    kidPicks: ["Floating pizza delivery in the water", "Steam caves walk", "Viking horses ride"],
    prices: { meal: 28, coffee: 5.5, taxi: 22, hotel: 240, attraction: 65 },
    priceNote: "Iceland is expensive. The lagoon itself is the big ticket; eat lunch at a bakery, not the hotel.",
  },
  lofoten: {
    key: "lofoten", name: "Reine", country: "Norway (Lofoten)", flag: "🇳🇴",
    lat: 67.93, lng: 13.09, tz: "Europe/Oslo",
    currency: "NOK (~10.5 per $1)",
    bestView: "Reinebringen summit: 1,971 stone steps up to the whole fjord in one look. Go at 23:00 in June — the light never dies",
    bestMonths: "June to July for midnight sun, September for aurora without crowds",
    crowd: "The Reinebringen steps queue at midday. Climb early or late; the village empties by 18:00",
    kid: "Easy kayak water, troll-fjord boat trips, and midnight beach runs that kids never forget",
    adventure: ["Reinebringen climb (1.5h)", "Sea-eagle safari", "Surfing at Unstad (cold, wetsuits provided)"],
    kidPicks: ["Fisherman's cabin stay (rorbu)", "Sea-eagle boat safari", "Midnight sun beach play"],
    prices: { meal: 24, coffee: 5, taxi: 18, hotel: 185, attraction: 30 },
    priceNote: "Cabins with kitchens save a family real money: supermarkets are normal-priced, restaurants are not.",
  },
  faroe: {
    key: "faroe", name: "Sørvágsvatn", country: "Faroe Islands", flag: "🇫🇴",
    lat: 62.06, lng: -7.35, tz: "Atlantic/Faroe",
    currency: "DKK (~6.9 per $1)",
    bestView: "Trælanípa cliff itself: the lake appears to float above the ocean. The full optical illusion needs you 200m back along the rim",
    bestMonths: "May to August. Expect four seasons in one day, any day",
    crowd: "The private-land trail takes 800 hikers a day in summer. Go before 10:00 and you share it with sheep",
    kid: "Puffin colonies at Mykines (ferry from Sørvágur), grass-roofed villages, and weather that changes fast enough to feel like magic",
    adventure: ["Trælanípa rim walk (4km)", "Boat into the Vestmanna cliffs", "Múlafossur waterfall at Gásadalur"],
    kidPicks: ["Puffin island ferry", "Waterfall you can walk behind", "Grass-roof houses to spot"],
    prices: { meal: 26, coffee: 5, taxi: 16, hotel: 150, attraction: 20 },
    priceNote: "Trails on private land charge a hiker's fee in cash or card at the gate — that is normal, not a scam.",
  },
  whitehaven: {
    key: "whitehaven", name: "Hill Inlet", country: "Australia (Whitsundays)", flag: "🇦🇺",
    lat: -20.28, lng: 149.05, tz: "Australia/Brisbane",
    currency: "AUD (~1.5 per $1)",
    bestView: "Hill Inlet lookout at mid-tide: the swirl is sharpest when the tide is halfway in or out, not at low tide",
    bestMonths: "May to October: dry season, stinger-free, 24°C",
    crowd: "Day-trip boats land 09:30 to 14:00. Sailing trips that stay past 15:00 get the beach to themselves",
    kid: "Shallow warm lagoon water, no stingers June to July, and the purest white sand they will ever stomp in",
    adventure: ["Sailing the Whitsundays", "Great Barrier Reef snorkel trips", "Sea-kayak to Langford Island"],
    kidPicks: ["Sand that squeaks underfoot", "Lookout walk (400m, pram-able)", "Turtle spotting from the boat"],
    prices: { meal: 18, coffee: 4.5, taxi: 14, hotel: 190, attraction: 120 },
    priceNote: "The boat is the cost, not the beach. Compare sailing-day trips: cheap ones are day-cruises, good ones are sail.",
  },
  napali: {
    key: "napali", name: "Nāpali Coast", country: "Hawaii, USA", flag: "🇺🇸",
    lat: 22.17, lng: -159.60, tz: "Pacific/Honolulu",
    currency: "USD",
    bestView: "From the water: the sunset catamaran past the fluted cliffs. On land: Pu'u O Kila lookout when the clouds lift",
    bestMonths: "May to September (calm seas). Winter closes the coast to boats",
    crowd: "Kalalau Trail permits sell out months ahead. Boat tours are the quiet loophole: fewer people, better angle",
    kid: "Boat trips run from age 5. Snorkel stops in the lee of the cliffs are calm and full of turtles",
    adventure: ["Kalalau Trail to Hanakāpī'ai (permit-free 8km return)", "Sunset catamaran", "Helicopter doors-off flight"],
    kidPicks: ["Dolphins on the boat ride", "Snorkel with turtles", "Shave ice in Hanalei after"],
    prices: { meal: 22, coffee: 5, taxi: 15, hotel: 320, attraction: 140 },
    priceNote: "Hawaii hotel prices bite. Renting a cottage on the north shore often beats a resort for a family of four.",
  },
  wadirum: {
    key: "wadirum", name: "Wadi Rum", country: "Jordan", flag: "🇯🇴",
    lat: 29.58, lng: 35.42, tz: "Asia/Amman",
    currency: "JOD (~0.71 per $1)",
    bestView: "From a camel or 4x4 at Um Frouth rock bridge 30 minutes before sunset, when the sand goes red",
    bestMonths: "March to May, September to November. Summer passes 40°C",
    crowd: "Tours bunch at the big rock bridges 16:00 to 18:00. Camp overnight: after 19:00 the desert is yours",
    kid: "Bedouin camps, camel rides, scramble-proof sand dunes, and a night sky with zero light pollution. Kids sleep in the desert.",
    adventure: ["4x4 desert circuit", "Camel trek at dusk", "Bubble-dome night under the stars"],
    kidPicks: ["Sandboarding the red dunes", "Camel ride", "Stargazing from a Bedouin camp"],
    prices: { meal: 8, coffee: 1.5, taxi: 6, hotel: 90, attraction: 20 },
    priceNote: "Jordan is fair value. Agree the jeep tour price BEFORE getting in; anything quoted per person over $40 is tourist-priced.",
  },
  yasawa: {
    key: "yasawa", name: "Naviti Island", country: "Fiji", flag: "🇫🇯",
    lat: -17.42, lng: 177.19, tz: "Pacific/Fiji",
    currency: "FJD (~2.2 per $1)",
    bestView: "The northern end of the island at low tide, when the reef flat opens a walkable path between coral gardens",
    bestMonths: "May to October: dry, 26°C, calm water",
    crowd: "Resort day-trips cluster at Sawa-i-Lau caves mid-morning. Island villages stay empty all day",
    kid: "Fijians adore kids. Village visits, hermit-crab races, and water warm enough to stay in until dark",
    adventure: ["Sawa-i-Lau limestone caves", "Reef snorkel off the resort sand", "Manta ray snorkel (seasonal, May-Oct)"],
    kidPicks: ["Hermit crab races", "Coral-snorkel from the beach", "Fijian lovo feast night"],
    prices: { meal: 10, coffee: 2.5, taxi: 5, hotel: 130, attraction: 15 },
    priceNote: "Island resorts include meals in the rate. A kava ceremony tip is a F$5 note, not more.",
  },
  kyoto: {
    key: "kyoto", name: "Ryōan-ji", country: "Japan", flag: "🇯🇵",
    lat: 35.0347, lng: 135.7183, tz: "Asia/Tokyo",
    currency: "JPY (~150 per $1)",
    bestView: "The veranda of the hojo, far right end: the classic angle where the 15th stone hides. Arrive at opening, 08:00",
    bestMonths: "Late March to April (cherry blossom), November (maple fire)",
    crowd: "Tour buses hit 10:00 to 14:00. At 08:00 you can hear the gravel being raked",
    kid: "Zen gardens challenge kids to count the stones; the Ryoan-ji bathhouse-style restaurant lets them try hot matcha the old way",
    adventure: ["Fushimi Inari at dawn (10,000 gates)", "Arashiyama bamboo grove", "Kamo river evening walk"],
    kidPicks: ["Count-the-stones challenge", "Monkey park in Arashiyama", "Riding the JR Nara line trains"],
    prices: { meal: 9, coffee: 4, taxi: 12, hotel: 110, attraction: 5 },
    priceNote: "Kyoto temples cost less than a coffee. Save the budget for kaiseki one night and konbini breakfasts the rest.",
  },
};

// Fair-price verdict bands (ratio of quoted price to local median)
export function fairVerdict(ratio) {
  if (ratio <= 0.75) return { verdict: "A real deal", tone: "good", note: "Below what locals pay. Enjoy it." };
  if (ratio <= 1.15) return { verdict: "Fair price", tone: "good", note: "Right around the local median." };
  if (ratio <= 1.6) return { verdict: "Slightly high", tone: "ok", note: "A touch above local rates. Acceptable in a tourist zone." };
  if (ratio <= 2.2) return { verdict: "Tourist price", tone: "warn", note: "You are paying the visitor tax. Try two streets away." };
  return { verdict: "Overpriced", tone: "bad", note: "More than double the local median. Walk away or negotiate." };
}
