// GENERATED by scripts/kb-build.mjs — do not edit. Source: data/kb/*.json
export const KB = {
 "bali-ubud": {
  "key": "bali-ubud",
  "kind": "city",
  "name": "Bali (Ubud)",
  "city": "Bali (Ubud)",
  "country": "Indonesia",
  "flag": "🇮🇩",
  "lat": -8.51,
  "lng": 115.26,
  "tz": null,
  "currency": "IDR ~16000/$",
  "tags": [
   "yoga",
   "rice terraces",
   "tropical",
   "budget",
   "wellness",
   "digital nomad",
   "waterfalls"
  ],
  "deep": {
   "key": "bali-ubud",
   "city": "Bali (Ubud)",
   "country": "Indonesia",
   "flag": "🇮🇩",
   "lat": -8.51,
   "lng": 115.26,
   "currency": "IDR ~16000/$",
   "prices": {
    "meal_cheap": 2.8,
    "coffee": 1.8,
    "beer": 2.8,
    "taxi_3km": 2.5,
    "transit_ride": 0.5,
    "hotel_budget": 20,
    "hotel_mid": 55,
    "hotel_lux": 180,
    "internet_month": 12,
    "sim_data": 7,
    "meal_mid_rest": 15,
    "water_bottle": 0.4,
    "daily_budget": 35,
    "daily_mid": 104
   },
   "tags": [
    "yoga",
    "rice terraces",
    "tropical",
    "budget",
    "wellness",
    "digital nomad",
    "waterfalls"
   ],
   "best_for": [
    "wellness",
    "yoga retreats",
    "nature",
    "remote work"
   ],
   "groceries": {
    "milk_l": 1.7,
    "bread": 1.5,
    "eggs_12": 2.4,
    "rice_kg": 1.2,
    "chicken_kg": 3,
    "fruit_kg": 1.6,
    "market_meal": 1.5
   },
   "leisure": {
    "cinema": 5,
    "cocktail": 6,
    "gym_month": 30,
    "laundry": 1,
    "massage_hr": 9
   },
   "transport_extra": {
    "scooter_day": 6,
    "fuel_l": 0.9,
    "ridehail_km": 0.4
   },
   "activities": {
    "monkey_forest": 5,
    "rice_terrace": 2,
    "waterfall_tour": 30,
    "yoga_class": 12
   },
   "monthly": {
    "budget": 560,
    "comfortable": 1050
   },
   "seasons": "Dry May-Sep (best). Wet Oct-Apr, still warm. Ubud cooler than the coast.",
   "airports": "DPS +1.5h drive",
   "notes": "Scooter essential. Tourist tax on arrival.",
   "docs": {
    "entry": "Visa on arrival (VoA) ~IDR 500,000 / $35, 30 days + one 30-day extension.",
    "insurance": "Required by many villas; scooter accidents common — get cover.",
    "special": [
     "Scooter licence (international permit)",
     "Tourist tax IDR 150,000 paid on arrival"
    ],
    "health": "Hepatitis A recommended; rabies risk near monkeys.",
    "agency": "VoA is pay-at-desk; agencies that 'pre-arrange' it overcharge."
   }
  },
  "bestMonths": "Dry May-Sep (best). Wet Oct-Apr, still warm. Ubud cooler than the coast.",
  "crowd": "Scooter essential. Tourist tax on arrival.",
  "prices": {
   "meal": 2.8,
   "coffee": 1.8,
   "taxi": 2.5,
   "hotel": 55
  },
  "daily_budget": 35,
  "daily_mid": 104,
  "priceLevel": "moderate",
  "best_for": [
   "wellness",
   "yoga retreats",
   "nature",
   "remote work"
  ]
 },
 "barcelona": {
  "key": "barcelona",
  "kind": "city",
  "name": "Barcelona",
  "city": "Barcelona",
  "country": "Spain",
  "flag": "🇪🇸",
  "lat": 41.39,
  "lng": 2.17,
  "tz": null,
  "currency": "EUR ~0.92/$",
  "tags": [
   "beach",
   "architecture",
   "nightlife",
   "city",
   "foodie",
   "art"
  ],
  "deep": {
   "key": "barcelona",
   "city": "Barcelona",
   "country": "Spain",
   "flag": "🇪🇸",
   "lat": 41.39,
   "lng": 2.17,
   "currency": "EUR ~0.92/$",
   "prices": {
    "meal_cheap": 15,
    "coffee": 2.5,
    "beer": 3.5,
    "taxi_3km": 6,
    "transit_ride": 2.4,
    "hotel_budget": 70,
    "hotel_mid": 140,
    "hotel_lux": 320,
    "internet_month": 35,
    "sim_data": 20,
    "meal_mid_rest": 30,
    "water_bottle": 0.7,
    "daily_budget": 127,
    "daily_mid": 227
   },
   "tags": [
    "beach",
    "architecture",
    "nightlife",
    "city",
    "foodie",
    "art"
   ],
   "best_for": [
    "gaudi",
    "mediterranean",
    "tapas"
   ],
   "groceries": {
    "milk_l": 1.1,
    "bread": 1.5,
    "eggs_12": 3.5,
    "rice_kg": 1.4,
    "chicken_kg": 6.5,
    "fruit_kg": 2.3,
    "market_meal": 9
   },
   "leisure": {
    "cinema": 10,
    "cocktail": 12,
    "gym_month": 45,
    "laundry": 4.5
   },
   "transport_extra": {
    "metro_ride": 2.5,
    "fuel_l": 1.75,
    "ridehail_km": 1
   },
   "activities": {
    "sagrada": 26,
    "park_guell": 10,
    "casa_batllo": 35,
    "picasso": 12
   },
   "monthly": {
    "budget": 1450,
    "comfortable": 2400
   },
   "seasons": "Best May-Jun, Sep. Jul-Aug hottest and most crowded.",
   "airports": "BCN",
   "notes": "Book Gaudí sites online ahead. Pickpockets on La Rambla.",
   "docs": {
    "entry": "Schengen: 90/180 days.",
    "insurance": "EHIC for EU; travel insurance otherwise.",
    "special": [],
    "health": "None required.",
    "agency": "Same Schengen process as Lisbon."
   }
  },
  "bestMonths": "Best May-Jun, Sep. Jul-Aug hottest and most crowded.",
  "crowd": "Book Gaudí sites online ahead. Pickpockets on La Rambla.",
  "prices": {
   "meal": 15,
   "coffee": 2.5,
   "taxi": 6,
   "hotel": 140
  },
  "daily_budget": 127,
  "daily_mid": 227,
  "priceLevel": "pricey",
  "best_for": [
   "gaudi",
   "mediterranean",
   "tapas"
  ]
 },
 "cape-town": {
  "key": "cape-town",
  "kind": "city",
  "name": "Cape Town",
  "city": "Cape Town",
  "country": "South Africa",
  "flag": "🇿🇦",
  "lat": -33.92,
  "lng": 18.42,
  "tz": null,
  "currency": "ZAR ~18/$",
  "tags": [
   "ocean",
   "mountains",
   "wine",
   "adventure",
   "scenic"
  ],
  "deep": {
   "key": "cape-town",
   "city": "Cape Town",
   "country": "South Africa",
   "flag": "🇿🇦",
   "lat": -33.92,
   "lng": 18.42,
   "currency": "ZAR ~18/$",
   "prices": {
    "meal_cheap": 8,
    "coffee": 2,
    "beer": 2.8,
    "taxi_3km": 4,
    "transit_ride": 1.2,
    "hotel_budget": 35,
    "hotel_mid": 80,
    "hotel_lux": 240,
    "internet_month": 25,
    "sim_data": 12,
    "meal_mid_rest": 20,
    "water_bottle": 0.6,
    "daily_budget": 68,
    "daily_mid": 142
   },
   "tags": [
    "ocean",
    "mountains",
    "wine",
    "adventure",
    "scenic"
   ],
   "best_for": [
    "table mountain",
    "penguins",
    "wine country"
   ],
   "groceries": {
    "milk_l": 1,
    "bread": 1.1,
    "eggs_12": 2.2,
    "rice_kg": 1.4,
    "chicken_kg": 4.5,
    "fruit_kg": 1.4,
    "market_meal": 5
   },
   "leisure": {
    "cinema": 7,
    "cocktail": 6,
    "gym_month": 35,
    "laundry": 2,
    "wine_tasting": 12
   },
   "transport_extra": {
    "scooter_day": 15,
    "fuel_l": 1.3,
    "ridehail_km": 0.7
   },
   "activities": {
    "table_mountain": 22,
    "roben_island": 18,
    "cape_point": 12,
    "penguins": 9
   },
   "monthly": {
    "budget": 950,
    "comfortable": 1650
   },
   "seasons": "Best Nov-Mar (dry summer). Jun-Aug rainy, whales. Windy Sep-Oct.",
   "airports": "CPT",
   "notes": "Use Uber, not street taxis. Safety varies by neighbourhood.",
   "docs": {
    "entry": "Visa-free 90 days for many; some need visas in advance.",
    "insurance": "Recommended; public healthcare variable.",
    "special": [
     "2 blank pages required in passport",
     "Birth certificate for minors (strict rules)"
    ],
    "health": "None from most countries.",
    "agency": "Minor-travel rules are strict — unaccompanied/one-parent docs required."
   }
  },
  "bestMonths": "Best Nov-Mar (dry summer). Jun-Aug rainy, whales. Windy Sep-Oct.",
  "crowd": "Use Uber, not street taxis. Safety varies by neighbourhood.",
  "prices": {
   "meal": 8,
   "coffee": 2,
   "taxi": 4,
   "hotel": 80
  },
  "daily_budget": 68,
  "daily_mid": 142,
  "priceLevel": "pricey",
  "best_for": [
   "table mountain",
   "penguins",
   "wine country"
  ]
 },
 "chiang-mai": {
  "key": "chiang-mai",
  "kind": "city",
  "name": "Chiang Mai",
  "city": "Chiang Mai",
  "country": "Thailand",
  "flag": "🇹🇭",
  "lat": 18.79,
  "lng": 98.98,
  "tz": null,
  "currency": "THB ~35/$",
  "tags": [
   "mountains",
   "temples",
   "budget",
   "digital nomad",
   "calm",
   "tropical"
  ],
  "deep": {
   "key": "chiang-mai",
   "city": "Chiang Mai",
   "country": "Thailand",
   "flag": "🇹🇭",
   "lat": 18.79,
   "lng": 98.98,
   "currency": "THB ~35/$",
   "prices": {
    "meal_cheap": 2.2,
    "coffee": 1.4,
    "beer": 1.8,
    "taxi_3km": 1.8,
    "transit_ride": 0.7,
    "hotel_budget": 15,
    "hotel_mid": 35,
    "hotel_lux": 90,
    "internet_month": 14,
    "sim_data": 8,
    "meal_mid_rest": 10,
    "water_bottle": 0.35,
    "daily_budget": 29,
    "daily_mid": 71
   },
   "tags": [
    "mountains",
    "temples",
    "budget",
    "digital nomad",
    "calm",
    "tropical"
   ],
   "best_for": [
    "long stays",
    "cooking schools",
    "nature"
   ],
   "groceries": {
    "milk_l": 1.5,
    "bread": 1.2,
    "eggs_12": 2,
    "rice_kg": 1,
    "chicken_kg": 2.6,
    "fruit_kg": 1.3,
    "market_meal": 1.5
   },
   "leisure": {
    "cinema": 5,
    "cocktail": 5,
    "gym_month": 30,
    "laundry": 1,
    "massage_hr": 7
   },
   "transport_extra": {
    "scooter_day": 6,
    "fuel_l": 1,
    "ridehail_km": 0.4
   },
   "activities": {
    "doisuthep": 4,
    "elephant_sanctuary": 45,
    "cooking_class": 25
   },
   "monthly": {
    "budget": 500,
    "comfortable": 900
   },
   "seasons": "Best Nov-Feb. Mar-Apr burning season (smog). Jun-Oct green and cheap.",
   "airports": "CNX",
   "notes": "Classic long-stay base: monthly apartments $200-350.",
   "docs": {
    "entry": "Visa-exempt 60 days (like Bangkok).",
    "insurance": "Cheap and recommended; scooters again.",
    "special": [
     "International driving permit for scooters"
    ],
    "health": "None required; air quality Mar-Apr.",
    "agency": "Long-stay visas (e.g. DTV) via consulate — legit agents exist but verify licence."
   }
  },
  "bestMonths": "Best Nov-Feb. Mar-Apr burning season (smog). Jun-Oct green and cheap.",
  "crowd": "Classic long-stay base: monthly apartments $200-350.",
  "prices": {
   "meal": 2.2,
   "coffee": 1.4,
   "taxi": 1.8,
   "hotel": 35
  },
  "daily_budget": 29,
  "daily_mid": 71,
  "priceLevel": "moderate",
  "best_for": [
   "long stays",
   "cooking schools",
   "nature"
  ]
 },
 "cusco": {
  "key": "cusco",
  "kind": "city",
  "name": "Cusco",
  "city": "Cusco",
  "country": "Peru",
  "flag": "🇵🇪",
  "lat": -13.53,
  "lng": -71.97,
  "tz": null,
  "currency": "PEN ~3.7/$",
  "tags": [
   "mountains",
   "inca",
   "high altitude",
   "budget",
   "adventure",
   "historic"
  ],
  "deep": {
   "key": "cusco",
   "city": "Cusco",
   "country": "Peru",
   "flag": "🇵🇪",
   "lat": -13.53,
   "lng": -71.97,
   "currency": "PEN ~3.7/$",
   "prices": {
    "meal_cheap": 5,
    "coffee": 1.8,
    "beer": 2.5,
    "taxi_3km": 3,
    "transit_ride": 0.5,
    "hotel_budget": 22,
    "hotel_mid": 60,
    "hotel_lux": 160,
    "internet_month": 20,
    "sim_data": 10,
    "meal_mid_rest": 14,
    "water_bottle": 0.5,
    "daily_budget": 44,
    "daily_mid": 108
   },
   "tags": [
    "mountains",
    "inca",
    "high altitude",
    "budget",
    "adventure",
    "historic"
   ],
   "best_for": [
    "machu picchu",
    "hiking",
    "culture"
   ],
   "groceries": {
    "milk_l": 1.2,
    "bread": 1,
    "eggs_12": 2,
    "rice_kg": 1,
    "chicken_kg": 3.2,
    "fruit_kg": 1.2,
    "market_meal": 2.5
   },
   "leisure": {
    "cinema": 5,
    "cocktail": 5,
    "gym_month": 25,
    "laundry": 1.5
   },
   "transport_extra": {
    "fuel_l": 1.2,
    "ridehail_km": 0.5
   },
   "activities": {
    "machu_picchu": 60,
    "sacred_valley": 40,
    "rainbow_mountain": 30,
    "cathedral": 8
   },
   "monthly": {
    "budget": 700,
    "comfortable": 1200
   },
   "seasons": "Dry May-Sep (best for Machu Picchu). Dec-Mar rainy. Acclimatise 2 days.",
   "airports": "CUZ (via Lima)",
   "notes": "Machu Picchu tickets sell out; book circuits weeks ahead. Altitude 3400m.",
   "docs": {
    "entry": "Most nationalities: 90 days free on arrival.",
    "insurance": "Machu Picchu treks require rescue-capable insurance.",
    "special": [
     "Passport for Machu Picchu entry (same one booked with)",
     "Student ISIC card for discounts"
    ],
    "health": "Altitude 3400m — acclimatise; yellow fever for Amazon side.",
    "agency": "Book Machu Picchu through licensed operators only; check Cusco agency registry."
   }
  },
  "bestMonths": "Dry May-Sep (best for Machu Picchu). Dec-Mar rainy. Acclimatise 2 days.",
  "crowd": "Machu Picchu tickets sell out; book circuits weeks ahead. Altitude 3400m.",
  "prices": {
   "meal": 5,
   "coffee": 1.8,
   "taxi": 3,
   "hotel": 60
  },
  "daily_budget": 44,
  "daily_mid": 108,
  "priceLevel": "moderate",
  "best_for": [
   "machu picchu",
   "hiking",
   "culture"
  ]
 },
 "faroe": {
  "key": "faroe",
  "name": "Sørvágsvatn",
  "country": "Faroe Islands",
  "flag": "🇫🇴",
  "lat": 62.06,
  "lng": -7.35,
  "tz": "Atlantic/Faroe",
  "currency": "DKK (~6.9 per $1)",
  "bestView": "Trælanípa cliff itself: the lake appears to float above the ocean. The full optical illusion needs you 200m back along the rim",
  "bestMonths": "May to August. Expect four seasons in one day, any day",
  "crowd": "The private-land trail takes 800 hikers a day in summer. Go before 10:00 and you share it with sheep",
  "kid": "Puffin colonies at Mykines (ferry from Sørvágur), grass-roofed villages, and weather that changes fast enough to feel like magic",
  "adventure": [
   "Trælanípa rim walk (4km)",
   "Boat into the Vestmanna cliffs",
   "Múlafossur waterfall at Gásadalur"
  ],
  "kidPicks": [
   "Puffin island ferry",
   "Waterfall you can walk behind",
   "Grass-roof houses to spot"
  ],
  "prices": {
   "meal": 26,
   "coffee": 5,
   "taxi": 16,
   "hotel": 150,
   "attraction": 20
  },
  "priceNote": "Trails on private land charge a hiker's fee in cash or card at the gate — that is normal, not a scam.",
  "kind": "featured",
  "deep": null,
  "visa": {
   "zone": "Danish realm",
   "note": "NOT Schengen-customary: Faroe Islands have their own rules; a Schengen visa must be marked 'valid for Faroe Islands'.",
   "source": "https://www.vesturfar.fo/"
  },
  "daily_budget": 150,
  "daily_mid": 290,
  "priceLevel": "pricey",
  "best_for": [
   "cliff hikes",
   "puffins",
   "grass-roof villages"
  ]
 },
 "hoi-an": {
  "key": "hoi-an",
  "kind": "city",
  "name": "Hoi An",
  "city": "Hoi An",
  "country": "Vietnam",
  "flag": "🇻🇳",
  "lat": 15.88,
  "lng": 108.34,
  "tz": null,
  "currency": "VND ~25000/$",
  "tags": [
   "lanterns",
   "budget",
   "calm",
   "beach nearby",
   "tailors",
   "foodie"
  ],
  "deep": {
   "key": "hoi-an",
   "city": "Hoi An",
   "country": "Vietnam",
   "flag": "🇻🇳",
   "lat": 15.88,
   "lng": 108.34,
   "currency": "VND ~25000/$",
   "prices": {
    "meal_cheap": 2.2,
    "coffee": 1.2,
    "beer": 1.5,
    "taxi_3km": 1.5,
    "transit_ride": 0.4,
    "hotel_budget": 15,
    "hotel_mid": 40,
    "hotel_lux": 120,
    "internet_month": 12,
    "sim_data": 6,
    "meal_mid_rest": 10,
    "water_bottle": 0.35,
    "daily_budget": 28,
    "daily_mid": 75
   },
   "tags": [
    "lanterns",
    "budget",
    "calm",
    "beach nearby",
    "tailors",
    "foodie"
   ],
   "best_for": [
    "old town",
    "cooking classes",
    "tailored clothes"
   ],
   "groceries": {
    "milk_l": 1.4,
    "bread": 1,
    "eggs_12": 1.8,
    "rice_kg": 0.9,
    "chicken_kg": 2.5,
    "fruit_kg": 1,
    "cao_lau": 1.5
   },
   "leisure": {
    "cinema": 4,
    "cocktail": 4,
    "gym_month": 28,
    "laundry": 0.8,
    "tailor_shirt": 20
   },
   "transport_extra": {
    "scooter_day": 5,
    "fuel_l": 0.9,
    "ridehail_km": 0.3
   },
   "activities": {
    "old_town": 5,
    "cooking_class": 22,
    "my_son": 25,
    "beach_bike": 2
   },
   "monthly": {
    "budget": 480,
    "comfortable": 850
   },
   "seasons": "Best Feb-Apr. Sep-Nov typhoon risk. May-Aug hot but beach season.",
   "airports": "DAD +45min",
   "notes": "Full-moon lantern night monthly. Test tailor with one item first.",
   "docs": {
    "entry": "E-visa 90 days multi-entry for most ($25), or visa-exempt for some ASEAN.",
    "insurance": "Recommended.",
    "special": [
     "E-visa printed copy (borders can be picky)",
     "Passport photo digital file"
    ],
    "health": "None required.",
    "agency": "E-visa is DIY on the official government site; third-party sites charge 3x."
   }
  },
  "bestMonths": "Best Feb-Apr. Sep-Nov typhoon risk. May-Aug hot but beach season.",
  "crowd": "Full-moon lantern night monthly. Test tailor with one item first.",
  "prices": {
   "meal": 2.2,
   "coffee": 1.2,
   "taxi": 1.5,
   "hotel": 40
  },
  "daily_budget": 28,
  "daily_mid": 75,
  "priceLevel": "moderate",
  "best_for": [
   "old town",
   "cooking classes",
   "tailored clothes"
  ]
 },
 "iceland": {
  "key": "iceland",
  "name": "Blue Lagoon",
  "country": "Iceland",
  "flag": "🇮🇸",
  "lat": 63.88,
  "lng": -22.45,
  "tz": "Atlantic/Reykjavik",
  "currency": "ISK (~140 per $1)",
  "bestView": "The north edge of the lagoon at sunset, steam drifting over the water with Mt. Þorbjörn behind",
  "bestMonths": "June to August for light, February to April for northern lights",
  "crowd": "Busy 11:00 to 16:00. Book the first or last slot of the day for near-empty water",
  "kid": "Kids 8+ love the floating mask bar and the algae mask ritual. Water is 38°C, safe for long soaks",
  "adventure": [
   "Lava-field hiking at Reykjanes",
   "Snorkelling the Silfra fissure (45 min away)",
   "Golden Circle drive"
  ],
  "kidPicks": [
   "Floating pizza delivery in the water",
   "Steam caves walk",
   "Viking horses ride"
  ],
  "prices": {
   "meal": 28,
   "coffee": 5.5,
   "taxi": 22,
   "hotel": 240,
   "attraction": 65
  },
  "priceNote": "Iceland is expensive. The lagoon itself is the big ticket; eat lunch at a bakery, not the hotel.",
  "kind": "featured",
  "deep": null,
  "visa": {
   "zone": "Schengen area",
   "note": "Schengen visa if required; 90 days in any 180 across the whole zone.",
   "source": "https://utl.is/en/"
  },
  "related": [
   "reykjavik"
  ],
  "daily_budget": 220,
  "daily_mid": 395,
  "priceLevel": "pricey",
  "best_for": [
   "northern lights",
   "lagoon soak",
   "lava fields"
  ]
 },
 "kotor": {
  "key": "kotor",
  "kind": "city",
  "name": "Kotor",
  "city": "Kotor",
  "country": "Montenegro",
  "flag": "🇲🇪",
  "lat": 42.42,
  "lng": 18.77,
  "tz": null,
  "currency": "EUR ~0.92/$",
  "tags": [
   "fjord-like bay",
   "historic",
   "budget europe",
   "calm",
   "mountains"
  ],
  "deep": {
   "key": "kotor",
   "city": "Kotor",
   "country": "Montenegro",
   "flag": "🇲🇪",
   "lat": 42.42,
   "lng": 18.77,
   "currency": "EUR ~0.92/$",
   "prices": {
    "meal_cheap": 10,
    "coffee": 2.5,
    "beer": 3,
    "taxi_3km": 4,
    "transit_ride": 1.5,
    "hotel_budget": 40,
    "hotel_mid": 85,
    "hotel_lux": 220,
    "internet_month": 25,
    "sim_data": 15,
    "meal_mid_rest": 20,
    "water_bottle": 0.6,
    "daily_budget": 80,
    "daily_mid": 148
   },
   "tags": [
    "fjord-like bay",
    "historic",
    "budget europe",
    "calm",
    "mountains"
   ],
   "best_for": [
    "bay of kotor",
    "old walls",
    "boat trips"
   ],
   "groceries": {
    "milk_l": 1.1,
    "bread": 1.2,
    "eggs_12": 2.8,
    "rice_kg": 1.3,
    "chicken_kg": 5.5,
    "fruit_kg": 1.8,
    "local_grill": 8
   },
   "leisure": {
    "cinema": 7,
    "cocktail": 7,
    "gym_month": 40,
    "laundry": 3,
    "kayak_hr": 10
   },
   "transport_extra": {
    "scooter_day": 15,
    "fuel_l": 1.7,
    "ridehail_km": 0.8
   },
   "activities": {
    "walls": 15,
    "blue_cave": 30,
    "lovćen": 5,
    "perast_boat": 10
   },
   "monthly": {
    "budget": 950,
    "comfortable": 1700
   },
   "seasons": "Best May-Jun, Sep. Jul-Aug cruise crowds. Winter quiet, some close.",
   "airports": "TIV 10min / DBV 2h",
   "notes": "Climb the walls at 7am: cool, empty, best light.",
   "docs": {
    "entry": "Visa-free 90 days for many; Schengen visa holders can enter.",
    "insurance": "EHIC doesn't cover Montenegro (not EU) — travel insurance needed.",
    "special": [],
    "health": "None required.",
    "agency": "None needed for tourism."
   }
  },
  "bestMonths": "Best May-Jun, Sep. Jul-Aug cruise crowds. Winter quiet, some close.",
  "crowd": "Climb the walls at 7am: cool, empty, best light.",
  "prices": {
   "meal": 10,
   "coffee": 2.5,
   "taxi": 4,
   "hotel": 85
  },
  "daily_budget": 80,
  "daily_mid": 148,
  "priceLevel": "pricey",
  "best_for": [
   "bay of kotor",
   "old walls",
   "boat trips"
  ]
 },
 "kyoto": {
  "key": "kyoto",
  "kind": "featured",
  "name": "Ryōan-ji",
  "city": "Kyoto",
  "country": "Japan",
  "flag": "🇯🇵",
  "lat": 35.0347,
  "lng": 135.7183,
  "tz": "Asia/Tokyo",
  "currency": "JPY (~150 per $1)",
  "tags": [
   "zen",
   "temples",
   "tradition",
   "calm",
   "gardens",
   "city"
  ],
  "deep": {
   "key": "kyoto",
   "city": "Kyoto",
   "country": "Japan",
   "flag": "🇯🇵",
   "lat": 35.01,
   "lng": 135.77,
   "currency": "JPY ~150/$",
   "prices": {
    "meal_cheap": 8,
    "coffee": 3.8,
    "beer": 3.5,
    "taxi_3km": 11,
    "transit_ride": 1.6,
    "hotel_budget": 55,
    "hotel_mid": 105,
    "hotel_lux": 300,
    "internet_month": 30,
    "sim_data": 25,
    "meal_mid_rest": 25,
    "water_bottle": 0.8,
    "daily_budget": 89,
    "daily_mid": 195
   },
   "tags": [
    "zen",
    "temples",
    "tradition",
    "calm",
    "gardens",
    "city"
   ],
   "best_for": [
    "temples",
    "cherry blossom",
    "culture"
   ],
   "groceries": {
    "milk_l": 1.9,
    "bread": 1.8,
    "eggs_12": 2.6,
    "rice_kg": 3,
    "chicken_kg": 6,
    "fruit_kg": 3.5,
    "conbini_meal": 4.5
   },
   "leisure": {
    "cinema": 12,
    "cocktail": 10,
    "gym_month": 50,
    "laundry": 3,
    "onsen": 8
   },
   "transport_extra": {
    "bus_ride": 1.5,
    "fuel_l": 1.2,
    "ridehail_km": 1.1
   },
   "activities": {
    "ryoanji": 5,
    "fushimi_inari": 0,
    "kinkakuji": 4,
    "tea_ceremony": 35
   },
   "monthly": {
    "budget": 1250,
    "comfortable": 2100
   },
   "seasons": "Peak late Mar-Apr (blossom) and Nov (maples). Jun rainy, cheap. Winter quiet.",
   "airports": "KIX +75min / ITM",
   "notes": "Conbini meals are genuinely good. IC card covers all transit.",
   "docs": {
    "entry": "Visa-free 90 days for ~70 nationalities; eVisa for others.",
    "insurance": "Strongly recommended — medical costs high for foreigners.",
    "special": [
     "Visit Japan Web registration (speeds immigration)"
    ],
    "health": "None required.",
    "agency": "eVisa via official MOFA site only — fakes exist."
   }
  },
  "bestMonths": "Late March to April (cherry blossom), November (maple fire)",
  "crowd": "Tour buses hit 10:00 to 14:00. At 08:00 you can hear the gravel being raked",
  "prices": {
   "meal": 9,
   "coffee": 4,
   "taxi": 12,
   "hotel": 110,
   "attraction": 5
  },
  "bestView": "The veranda of the hojo, far right end: the classic angle where the 15th stone hides. Arrive at opening, 08:00",
  "kid": "Zen gardens challenge kids to count the stones; the Ryoan-ji bathhouse-style restaurant lets them try hot matcha the old way",
  "adventure": [
   "Fushimi Inari at dawn (10,000 gates)",
   "Arashiyama bamboo grove",
   "Kamo river evening walk"
  ],
  "kidPicks": [
   "Count-the-stones challenge",
   "Monkey park in Arashiyama",
   "Riding the JR Nara line trains"
  ],
  "priceNote": "Kyoto temples cost less than a coffee. Save the budget for kaiseki one night and konbini breakfasts the rest.",
  "visa": {
   "zone": "Japan",
   "note": "Visa-free 90 days for ~70 nationalities. Others need a visa via embassy or the eVisa system.",
   "source": "https://www.mofa.go.jp/"
  },
  "daily_budget": 89,
  "daily_mid": 195,
  "priceLevel": "pricey",
  "best_for": [
   "temples",
   "cherry blossom",
   "culture"
  ]
 },
 "lisbon": {
  "key": "lisbon",
  "kind": "city",
  "name": "Lisbon",
  "city": "Lisbon",
  "country": "Portugal",
  "flag": "🇵🇹",
  "lat": 38.72,
  "lng": -9.14,
  "tz": null,
  "currency": "EUR ~0.92/$",
  "tags": [
   "ocean",
   "historic",
   "pastel streets",
   "foodie",
   "affordable europe",
   "city",
   "surf"
  ],
  "deep": {
   "key": "lisbon",
   "city": "Lisbon",
   "country": "Portugal",
   "flag": "🇵🇹",
   "lat": 38.72,
   "lng": -9.14,
   "currency": "EUR ~0.92/$",
   "prices": {
    "meal_cheap": 12,
    "coffee": 2.2,
    "beer": 3,
    "taxi_3km": 5,
    "transit_ride": 1.8,
    "hotel_budget": 55,
    "hotel_mid": 110,
    "hotel_lux": 260,
    "internet_month": 30,
    "sim_data": 20,
    "meal_mid_rest": 25,
    "water_bottle": 0.6,
    "daily_budget": 101,
    "daily_mid": 184
   },
   "tags": [
    "ocean",
    "historic",
    "pastel streets",
    "foodie",
    "affordable europe",
    "city",
    "surf"
   ],
   "best_for": [
    "european city break",
    "coastal walks",
    "pastries"
   ],
   "groceries": {
    "milk_l": 1,
    "bread": 1.4,
    "eggs_12": 3.2,
    "rice_kg": 1.3,
    "chicken_kg": 6,
    "fruit_kg": 2.2,
    "market_meal": 8
   },
   "leisure": {
    "cinema": 9,
    "cocktail": 10,
    "gym_month": 35,
    "laundry": 4,
    "fado_night": 25
   },
   "transport_extra": {
    "tram_day": 2.2,
    "fuel_l": 1.8,
    "ridehail_km": 0.9
   },
   "activities": {
    "jeronymos": 12,
    "castle": 15,
    "sintra_day": 25,
    "fado_show": 30
   },
   "monthly": {
    "budget": 1150,
    "comfortable": 1900
   },
   "seasons": "Best Mar-Jun, Sep-Oct. Jul-Aug hot and busiest. Winter mild.",
   "airports": "LIS",
   "notes": "Pastéis de nata €1.30. Skip tram 28 queues; walk Alfama.",
   "docs": {
    "entry": "Schengen: 90/180 days; EU/EEA citizens free movement.",
    "insurance": "EHIC covers EU citizens; others get travel insurance.",
    "special": [
     "Schengen insurance €30k if visa required"
    ],
    "health": "No special vaccines.",
    "agency": "Schengen visas via VFS Global centres; never pay 'guarantee' agents."
   }
  },
  "bestMonths": "Best Mar-Jun, Sep-Oct. Jul-Aug hot and busiest. Winter mild.",
  "crowd": "Pastéis de nata €1.30. Skip tram 28 queues; walk Alfama.",
  "prices": {
   "meal": 12,
   "coffee": 2.2,
   "taxi": 5,
   "hotel": 110
  },
  "daily_budget": 101,
  "daily_mid": 184,
  "priceLevel": "pricey",
  "best_for": [
   "european city break",
   "coastal walks",
   "pastries"
  ]
 },
 "lofoten": {
  "key": "lofoten",
  "name": "Reine",
  "country": "Norway (Lofoten)",
  "flag": "🇳🇴",
  "lat": 67.93,
  "lng": 13.09,
  "tz": "Europe/Oslo",
  "currency": "NOK (~10.5 per $1)",
  "bestView": "Reinebringen summit: 1,971 stone steps up to the whole fjord in one look. Go at 23:00 in June — the light never dies",
  "bestMonths": "June to July for midnight sun, September for aurora without crowds",
  "crowd": "The Reinebringen steps queue at midday. Climb early or late; the village empties by 18:00",
  "kid": "Easy kayak water, troll-fjord boat trips, and midnight beach runs that kids never forget",
  "adventure": [
   "Reinebringen climb (1.5h)",
   "Sea-eagle safari",
   "Surfing at Unstad (cold, wetsuits provided)"
  ],
  "kidPicks": [
   "Fisherman's cabin stay (rorbu)",
   "Sea-eagle boat safari",
   "Midnight sun beach play"
  ],
  "prices": {
   "meal": 24,
   "coffee": 5,
   "taxi": 18,
   "hotel": 185,
   "attraction": 30
  },
  "priceNote": "Cabins with kitchens save a family real money: supermarkets are normal-priced, restaurants are not.",
  "kind": "featured",
  "deep": null,
  "visa": {
   "zone": "Schengen area",
   "note": "Schengen rules — same 90/180 day clock as the rest of the zone.",
   "source": "https://www.udi.no/en/"
  },
  "daily_budget": 180,
  "daily_mid": 330,
  "priceLevel": "pricey",
  "best_for": [
   "midnight sun",
   "fjord hikes",
   "sea eagles"
  ]
 },
 "marrakech": {
  "key": "marrakech",
  "kind": "city",
  "name": "Marrakech",
  "city": "Marrakech",
  "country": "Morocco",
  "flag": "🇲🇦",
  "lat": 31.63,
  "lng": -7.99,
  "tz": null,
  "currency": "MAD ~10/$",
  "tags": [
   "souks",
   "desert",
   "riads",
   "budget",
   "culture",
   "warm"
  ],
  "deep": {
   "key": "marrakech",
   "city": "Marrakech",
   "country": "Morocco",
   "flag": "🇲🇦",
   "lat": 31.63,
   "lng": -7.99,
   "currency": "MAD ~10/$",
   "prices": {
    "meal_cheap": 5,
    "coffee": 2,
    "beer": 3.5,
    "taxi_3km": 2.5,
    "transit_ride": 0.6,
    "hotel_budget": 30,
    "hotel_mid": 70,
    "hotel_lux": 200,
    "internet_month": 18,
    "sim_data": 10,
    "meal_mid_rest": 15,
    "water_bottle": 0.5,
    "daily_budget": 52,
    "daily_mid": 119
   },
   "tags": [
    "souks",
    "desert",
    "riads",
    "budget",
    "culture",
    "warm"
   ],
   "best_for": [
    "medina",
    "desert trips",
    "hammams"
   ],
   "groceries": {
    "milk_l": 0.9,
    "bread": 0.6,
    "eggs_12": 1.8,
    "rice_kg": 1,
    "chicken_kg": 3,
    "fruit_kg": 1.2,
    "market_meal": 3
   },
   "leisure": {
    "cinema": 6,
    "cocktail": 9,
    "gym_month": 30,
    "laundry": 1.2,
    "hammam": 12
   },
   "transport_extra": {
    "scooter_day": 12,
    "fuel_l": 1.3,
    "ridehail_km": 0.4
   },
   "activities": {
    "majorelle": 10,
    "medina_tour": 20,
    "desert_2day": 60,
    "hammam": 12
   },
   "monthly": {
    "budget": 700,
    "comfortable": 1300
   },
   "seasons": "Best Mar-May, Oct-Nov. Jun-Aug over 40°C. Winter nights cold.",
   "airports": "RAK",
   "notes": "Agree taxi price before entering. Riads beat hotels on value.",
   "docs": {
    "entry": "Visa-free 90 days for ~70 nationalities.",
    "insurance": "Recommended.",
    "special": [
     "ID for hotel check-in (passport)"
    ],
    "health": "Hepatitis A recommended.",
    "agency": "Official 'guides' wear badges in the medina; unlicensed 'helpers' expect tips."
   }
  },
  "bestMonths": "Best Mar-May, Oct-Nov. Jun-Aug over 40°C. Winter nights cold.",
  "crowd": "Agree taxi price before entering. Riads beat hotels on value.",
  "prices": {
   "meal": 5,
   "coffee": 2,
   "taxi": 2.5,
   "hotel": 70
  },
  "daily_budget": 52,
  "daily_mid": 119,
  "priceLevel": "moderate",
  "best_for": [
   "medina",
   "desert trips",
   "hammams"
  ]
 },
 "medellin": {
  "key": "medellin",
  "kind": "city",
  "name": "Medellín",
  "city": "Medellín",
  "country": "Colombia",
  "flag": "🇨🇴",
  "lat": 6.24,
  "lng": -75.58,
  "tz": null,
  "currency": "COP ~4000/$",
  "tags": [
   "city",
   "eternal spring",
   "digital nomad",
   "nightlife",
   "budget-ish"
  ],
  "deep": {
   "key": "medellín",
   "city": "Medellín",
   "country": "Colombia",
   "flag": "🇨🇴",
   "lat": 6.24,
   "lng": -75.58,
   "currency": "COP ~4000/$",
   "prices": {
    "meal_cheap": 5,
    "coffee": 1.8,
    "beer": 2,
    "taxi_3km": 3,
    "transit_ride": 0.8,
    "hotel_budget": 28,
    "hotel_mid": 65,
    "hotel_lux": 180,
    "internet_month": 22,
    "sim_data": 10,
    "meal_mid_rest": 14,
    "water_bottle": 0.5,
    "daily_budget": 50,
    "daily_mid": 113
   },
   "tags": [
    "city",
    "eternal spring",
    "digital nomad",
    "nightlife",
    "budget-ish"
   ],
   "best_for": [
    "comuna 13",
    "coffee",
    "spring weather"
   ],
   "groceries": {
    "milk_l": 1.1,
    "bread": 1,
    "eggs_12": 1.9,
    "rice_kg": 1,
    "chicken_kg": 3,
    "fruit_kg": 1.1,
    "arepa": 0.8
   },
   "leisure": {
    "cinema": 5,
    "cocktail": 7,
    "gym_month": 30,
    "laundry": 1.3,
    "football_match": 15
   },
   "transport_extra": {
    "metro_ride": 0.7,
    "fuel_l": 1,
    "ridehail_km": 0.5
   },
   "activities": {
    "comuna13": 15,
    "guatape_day": 25,
    "cable_car": 3,
    "parque_arvi": 5
   },
   "monthly": {
    "budget": 750,
    "comfortable": 1400
   },
   "seasons": "Eternal spring (22-28°C) year-round. Drier Dec-Mar, Jul-Aug.",
   "airports": "MDE / JOH",
   "notes": "Metro + cable car: cleanest system in Latin America. Comuna 13 with licensed guide.",
   "docs": {
    "entry": "Visa-free 90 days (extendable) for most.",
    "insurance": "Recommended.",
    "special": [
     "Return ticket proof (checked at check-in)"
    ],
    "health": "None required; altitude mild.",
    "agency": "None needed."
   }
  },
  "bestMonths": "Eternal spring (22-28°C) year-round. Drier Dec-Mar, Jul-Aug.",
  "crowd": "Metro + cable car: cleanest system in Latin America. Comuna 13 with licensed guide.",
  "prices": {
   "meal": 5,
   "coffee": 1.8,
   "taxi": 3,
   "hotel": 65
  },
  "daily_budget": 50,
  "daily_mid": 113,
  "priceLevel": "moderate",
  "best_for": [
   "comuna 13",
   "coffee",
   "spring weather"
  ]
 },
 "mexico-city": {
  "key": "mexico-city",
  "kind": "city",
  "name": "Mexico City",
  "city": "Mexico City",
  "country": "Mexico",
  "flag": "🇲🇽",
  "lat": 19.43,
  "lng": -99.13,
  "tz": null,
  "currency": "MXN ~18/$",
  "tags": [
   "city",
   "foodie",
   "art",
   "museums",
   "nightlife",
   "budget-ish"
  ],
  "deep": {
   "key": "mexico-city",
   "city": "Mexico City",
   "country": "Mexico",
   "flag": "🇲🇽",
   "lat": 19.43,
   "lng": -99.13,
   "currency": "MXN ~18/$",
   "prices": {
    "meal_cheap": 6,
    "coffee": 2.2,
    "beer": 2.5,
    "taxi_3km": 3,
    "transit_ride": 0.4,
    "hotel_budget": 40,
    "hotel_mid": 90,
    "hotel_lux": 220,
    "internet_month": 25,
    "sim_data": 12,
    "meal_mid_rest": 18,
    "water_bottle": 0.5,
    "daily_budget": 64,
    "daily_mid": 146
   },
   "tags": [
    "city",
    "foodie",
    "art",
    "museums",
    "nightlife",
    "budget-ish"
   ],
   "best_for": [
    "street tacos",
    "museums",
    "urban energy"
   ],
   "groceries": {
    "milk_l": 1.2,
    "bread": 1.4,
    "eggs_12": 2,
    "rice_kg": 1.2,
    "chicken_kg": 3.4,
    "fruit_kg": 1.4,
    "market_meal": 3.5
   },
   "leisure": {
    "cinema": 5,
    "cocktail": 8,
    "gym_month": 35,
    "laundry": 1.8,
    "lucha_libre": 8
   },
   "transport_extra": {
    "metro_ride": 0.4,
    "fuel_l": 1.3,
    "ridehail_km": 0.6
   },
   "activities": {
    "museums": 3,
    "teotihuacan_day": 30,
    "xochimilco": 25,
    "lucha_libre": 8
   },
   "monthly": {
    "budget": 850,
    "comfortable": 1500
   },
   "seasons": "Best Mar-May, Oct-Nov (dry, warm). Jun-Sep rainy afternoons. Altitude 2240m.",
   "airports": "MEX / NLU",
   "notes": "Metro costs $0.25. Tacos al pastor $1-2 at night stands.",
   "docs": {
    "entry": "Visa-free for ~70 nationalities; FMM tourist card digital.",
    "insurance": "Recommended.",
    "special": [
     "Tourist card kept until departure"
    ],
    "health": "Altitude 2240m; tap water never.",
    "agency": "None needed for tourism."
   }
  },
  "bestMonths": "Best Mar-May, Oct-Nov (dry, warm). Jun-Sep rainy afternoons. Altitude 2240m.",
  "crowd": "Metro costs $0.25. Tacos al pastor $1-2 at night stands.",
  "prices": {
   "meal": 6,
   "coffee": 2.2,
   "taxi": 3,
   "hotel": 90
  },
  "daily_budget": 64,
  "daily_mid": 146,
  "priceLevel": "pricey",
  "best_for": [
   "street tacos",
   "museums",
   "urban energy"
  ]
 },
 "napali": {
  "key": "napali",
  "name": "Nāpali Coast",
  "country": "Hawaii, USA",
  "flag": "🇺🇸",
  "lat": 22.17,
  "lng": -159.6,
  "tz": "Pacific/Honolulu",
  "currency": "USD",
  "bestView": "From the water: the sunset catamaran past the fluted cliffs. On land: Pu'u O Kila lookout when the clouds lift",
  "bestMonths": "May to September (calm seas). Winter closes the coast to boats",
  "crowd": "Kalalau Trail permits sell out months ahead. Boat tours are the quiet loophole: fewer people, better angle",
  "kid": "Boat trips run from age 5. Snorkel stops in the lee of the cliffs are calm and full of turtles",
  "adventure": [
   "Kalalau Trail to Hanakāpī'ai (permit-free 8km return)",
   "Sunset catamaran",
   "Helicopter doors-off flight"
  ],
  "kidPicks": [
   "Dolphins on the boat ride",
   "Snorkel with turtles",
   "Shave ice in Hanalei after"
  ],
  "prices": {
   "meal": 22,
   "coffee": 5,
   "taxi": 15,
   "hotel": 320,
   "attraction": 140
  },
  "priceNote": "Hawaii hotel prices bite. Renting a cottage on the north shore often beats a resort for a family of four.",
  "kind": "featured",
  "deep": null,
  "visa": {
   "zone": "United States",
   "note": "ESTA for visa-waiver countries (apply 72h+ before), otherwise a B-2 visa via interview.",
   "source": "https://travel.state.gov/"
  },
  "daily_budget": 210,
  "daily_mid": 370,
  "priceLevel": "pricey",
  "best_for": [
   "coast boat tours",
   "kalalau lookout",
   "snorkel"
  ]
 },
 "pokhara": {
  "key": "pokhara",
  "kind": "city",
  "name": "Pokhara",
  "city": "Pokhara",
  "country": "Nepal",
  "flag": "🇳🇵",
  "lat": 28.21,
  "lng": 83.99,
  "tz": null,
  "currency": "NPR ~133/$",
  "tags": [
   "mountains",
   "himalayas",
   "lakes",
   "budget",
   "adventure",
   "calm"
  ],
  "deep": {
   "key": "pokhara",
   "city": "Pokhara",
   "country": "Nepal",
   "flag": "🇳🇵",
   "lat": 28.21,
   "lng": 83.99,
   "currency": "NPR ~133/$",
   "prices": {
    "meal_cheap": 3.5,
    "coffee": 1.5,
    "beer": 2.5,
    "taxi_3km": 2,
    "transit_ride": 0.3,
    "hotel_budget": 15,
    "hotel_mid": 40,
    "hotel_lux": 120,
    "internet_month": 15,
    "sim_data": 8,
    "meal_mid_rest": 9,
    "water_bottle": 0.4,
    "daily_budget": 31,
    "daily_mid": 75
   },
   "tags": [
    "mountains",
    "himalayas",
    "lakes",
    "budget",
    "adventure",
    "calm"
   ],
   "best_for": [
    "annapurna",
    "paragliding",
    "sunrise views"
   ],
   "groceries": {
    "milk_l": 1,
    "bread": 0.9,
    "eggs_12": 1.7,
    "rice_kg": 0.9,
    "chicken_kg": 3,
    "fruit_kg": 1,
    "dal_bhat": 2.5
   },
   "leisure": {
    "cinema": 4,
    "cocktail": 4,
    "gym_month": 25,
    "laundry": 0.8,
    "boat_lake": 6
   },
   "transport_extra": {
    "scooter_day": 8,
    "fuel_l": 1.1,
    "ridehail_km": 0.3
   },
   "activities": {
    "paragliding": 85,
    "annapurna_permit": 30,
    "sarangkot_sunrise": 12
   },
   "monthly": {
    "budget": 450,
    "comfortable": 800
   },
   "seasons": "Trekking Oct-Nov, Mar-Apr (clear skies). Monsoon Jun-Sep. Cold winter nights.",
   "airports": "PKR (or 6h bus)",
   "notes": "Gateway to Annapurna. Permits via agencies in town.",
   "docs": {
    "entry": "Visa on arrival for most: 15/30/90 days ($30/50/125).",
    "insurance": "ESSENTIAL for trekking — rescue helicopter evacuations cost $5,000+.",
    "special": [
     "Annapurna Conservation Area Permit $25",
     "TIMS card",
     "Passport copies + photos for permits"
    ],
    "health": "Altitude; water treatment.",
    "agency": "Permits via official NTB/TAAN offices in Pokhara; trekking agencies must be TAAN-registered — check the registry."
   }
  },
  "bestMonths": "Trekking Oct-Nov, Mar-Apr (clear skies). Monsoon Jun-Sep. Cold winter nights.",
  "crowd": "Gateway to Annapurna. Permits via agencies in town.",
  "prices": {
   "meal": 3.5,
   "coffee": 1.5,
   "taxi": 2,
   "hotel": 40
  },
  "daily_budget": 31,
  "daily_mid": 75,
  "priceLevel": "moderate",
  "best_for": [
   "annapurna",
   "paragliding",
   "sunrise views"
  ]
 },
 "queenstown": {
  "key": "queenstown",
  "kind": "city",
  "name": "Queenstown",
  "city": "Queenstown",
  "country": "New Zealand",
  "flag": "🇳🇿",
  "lat": -45.03,
  "lng": 168.66,
  "tz": null,
  "currency": "NZD ~0.6/$",
  "tags": [
   "adventure",
   "mountains",
   "lakes",
   "expensive",
   "bungee",
   "hiking"
  ],
  "deep": {
   "key": "queenstown",
   "city": "Queenstown",
   "country": "New Zealand",
   "flag": "🇳🇿",
   "lat": -45.03,
   "lng": 168.66,
   "currency": "NZD ~0.6/$",
   "prices": {
    "meal_cheap": 18,
    "coffee": 4.2,
    "beer": 7,
    "taxi_3km": 10,
    "transit_ride": 2,
    "hotel_budget": 75,
    "hotel_mid": 150,
    "hotel_lux": 350,
    "internet_month": 30,
    "sim_data": 25,
    "meal_mid_rest": 35,
    "water_bottle": 0.9,
    "daily_budget": 140,
    "daily_mid": 258
   },
   "tags": [
    "adventure",
    "mountains",
    "lakes",
    "expensive",
    "bungee",
    "hiking"
   ],
   "best_for": [
    "adrenaline capital",
    "lord of the rings",
    "alpine"
   ],
   "groceries": {
    "milk_l": 1.5,
    "bread": 1.8,
    "eggs_12": 4.5,
    "rice_kg": 2,
    "chicken_kg": 8,
    "fruit_kg": 2.5,
    "meat_pie": 3.5
   },
   "leisure": {
    "cinema": 11,
    "cocktail": 12,
    "gym_month": 50,
    "laundry": 4,
    "gondola": 35
   },
   "transport_extra": {
    "fuel_l": 1.7,
    "ridehail_km": 1.2
   },
   "activities": {
    "bungee": 135,
    "skydive": 250,
    "milford_day": 150,
    "jet_boat": 80
   },
   "monthly": {
    "budget": 1800,
    "comfortable": 3000
   },
   "seasons": "Dec-Feb summer, busiest. Jun-Aug ski. Mar-Apr golden autumn, cheaper.",
   "airports": "ZQN",
   "notes": "Book adventure sports ahead; weather cancels often.",
   "docs": {
    "entry": "NZeTA required before flying (~NZ$23 + levy), even for visa-free nationalities.",
    "insurance": "Recommended; adventure sports exclusions matter — declare bungee/skydive.",
    "special": [
     "NZeTA via app/website before boarding",
     "Departure fee at some airports"
    ],
    "health": "None required.",
    "agency": "NZeTA is DIY-only; any 'agent' charging more is a scam."
   }
  },
  "bestMonths": "Dec-Feb summer, busiest. Jun-Aug ski. Mar-Apr golden autumn, cheaper.",
  "crowd": "Book adventure sports ahead; weather cancels often.",
  "prices": {
   "meal": 18,
   "coffee": 4.2,
   "taxi": 10,
   "hotel": 150
  },
  "daily_budget": 140,
  "daily_mid": 258,
  "priceLevel": "pricey",
  "best_for": [
   "adrenaline capital",
   "lord of the rings",
   "alpine"
  ]
 },
 "reykjavik": {
  "key": "reykjavik",
  "kind": "city",
  "name": "Reykjavik",
  "city": "Reykjavik",
  "country": "Iceland",
  "flag": "🇮🇸",
  "lat": 64.15,
  "lng": -21.94,
  "tz": null,
  "currency": "ISK ~140/$",
  "tags": [
   "aurora",
   "geothermal",
   "nature",
   "expensive",
   "adventure",
   "dark nights"
  ],
  "deep": {
   "key": "reykjavik",
   "city": "Reykjavik",
   "country": "Iceland",
   "flag": "🇮🇸",
   "lat": 64.15,
   "lng": -21.94,
   "currency": "ISK ~140/$",
   "prices": {
    "meal_cheap": 28,
    "coffee": 5.5,
    "beer": 9,
    "taxi_3km": 22,
    "transit_ride": 3.5,
    "hotel_budget": 120,
    "hotel_mid": 240,
    "hotel_lux": 500,
    "internet_month": 35,
    "sim_data": 25,
    "meal_mid_rest": 45,
    "water_bottle": 1,
    "daily_budget": 220,
    "daily_mid": 395
   },
   "tags": [
    "aurora",
    "geothermal",
    "nature",
    "expensive",
    "adventure",
    "dark nights"
   ],
   "best_for": [
    "northern lights",
    "blue lagoon",
    "road trips"
   ],
   "groceries": {
    "milk_l": 1.4,
    "bread": 2.5,
    "eggs_12": 5,
    "rice_kg": 2.5,
    "chicken_kg": 9,
    "fruit_kg": 3,
    "hot_dog": 4
   },
   "leisure": {
    "cinema": 15,
    "cocktail": 14,
    "gym_month": 60,
    "laundry": 6,
    "pool_entry": 7
   },
   "transport_extra": {
    "fuel_l": 2.3,
    "ridehail_km": 1.8,
    "bus_day": 9
   },
   "activities": {
    "blue_lagoon": 65,
    "golden_circle": 80,
    "aurora_tour": 70,
    "whales": 90
   },
   "monthly": {
    "budget": 2100,
    "comfortable": 3400
   },
   "seasons": "Jun-Aug midnight sun and hiking. Sep-Mar aurora. Expensive: buy alcohol duty-free.",
   "airports": "KEF +45min bus",
   "notes": "Tap water glacier-fresh. Bónus supermarkets halve food costs.",
   "docs": {
    "entry": "Schengen: 90/180 days.",
    "insurance": "EHIC for EU; otherwise travel insurance (costs high).",
    "special": [
     "Schengen insurance €30k if visa required"
    ],
    "health": "None required.",
    "agency": "Schengen via VFS; nothing else needed."
   }
  },
  "bestMonths": "Jun-Aug midnight sun and hiking. Sep-Mar aurora. Expensive: buy alcohol duty-free.",
  "crowd": "Tap water glacier-fresh. Bónus supermarkets halve food costs.",
  "prices": {
   "meal": 28,
   "coffee": 5.5,
   "taxi": 22,
   "hotel": 240
  },
  "related": [
   "iceland"
  ],
  "daily_budget": 220,
  "daily_mid": 395,
  "priceLevel": "pricey",
  "best_for": [
   "northern lights",
   "blue lagoon",
   "road trips"
  ]
 },
 "santorini": {
  "key": "santorini",
  "kind": "city",
  "name": "Santorini",
  "city": "Santorini",
  "country": "Greece",
  "flag": "🇬🇷",
  "lat": 36.39,
  "lng": 25.46,
  "tz": null,
  "currency": "EUR ~0.92/$",
  "tags": [
   "islands",
   "romantic",
   "views",
   "calm",
   "luxury-ish",
   "sunset"
  ],
  "deep": {
   "key": "santorini",
   "city": "Santorini",
   "country": "Greece",
   "flag": "🇬🇷",
   "lat": 36.39,
   "lng": 25.46,
   "currency": "EUR ~0.92/$",
   "prices": {
    "meal_cheap": 20,
    "coffee": 3.5,
    "beer": 5,
    "taxi_3km": 8,
    "transit_ride": 2,
    "hotel_budget": 90,
    "hotel_mid": 180,
    "hotel_lux": 450,
    "internet_month": 30,
    "sim_data": 20,
    "meal_mid_rest": 35,
    "water_bottle": 0.7,
    "daily_budget": 161,
    "daily_mid": 283
   },
   "tags": [
    "islands",
    "romantic",
    "views",
    "calm",
    "luxury-ish",
    "sunset"
   ],
   "best_for": [
    "caldera views",
    "white villages",
    "honeymoon"
   ],
   "groceries": {
    "milk_l": 1.3,
    "bread": 1.6,
    "eggs_12": 3.8,
    "rice_kg": 1.6,
    "chicken_kg": 7,
    "fruit_kg": 2.4,
    "gyros": 4.5
   },
   "leisure": {
    "cinema": 10,
    "cocktail": 13,
    "gym_month": 50,
    "laundry": 4,
    "caldera_cruise": 70
   },
   "transport_extra": {
    "scooter_day": 18,
    "fuel_l": 1.9,
    "ridehail_km": 1
   },
   "activities": {
    "oia_sunset": 0,
    "wine_tasting": 25,
    "akrotiri": 15,
    "catamaran": 110
   },
   "monthly": {
    "budget": 1500,
    "comfortable": 2800
   },
   "seasons": "Best May-Jun, Sep-Oct. Jul-Aug peak prices and crowds. Nov-Apr quiet, many close.",
   "airports": "JTR (or ferry from Athens)",
   "notes": "Stay in Fira/Kamari not Oia to halve costs. Imerovigli sunset is free.",
   "docs": {
    "entry": "Schengen: 90/180 days.",
    "insurance": "EHIC for EU; travel insurance otherwise.",
    "special": [],
    "health": "None required.",
    "agency": "Schengen via VFS."
   }
  },
  "bestMonths": "Best May-Jun, Sep-Oct. Jul-Aug peak prices and crowds. Nov-Apr quiet, many close.",
  "crowd": "Stay in Fira/Kamari not Oia to halve costs. Imerovigli sunset is free.",
  "prices": {
   "meal": 20,
   "coffee": 3.5,
   "taxi": 8,
   "hotel": 180
  },
  "daily_budget": 161,
  "daily_mid": 283,
  "priceLevel": "pricey",
  "best_for": [
   "caldera views",
   "white villages",
   "honeymoon"
  ]
 },
 "tbilisi": {
  "key": "tbilisi",
  "kind": "city",
  "name": "Tbilisi",
  "city": "Tbilisi",
  "country": "Georgia",
  "flag": "🇬🇪",
  "lat": 41.72,
  "lng": 44.78,
  "tz": null,
  "currency": "GEL ~2.7/$",
  "tags": [
   "budget europe",
   "wine",
   "mountains",
   "city",
   "digital nomad"
  ],
  "deep": {
   "key": "tbilisi",
   "city": "Tbilisi",
   "country": "Georgia",
   "flag": "🇬🇪",
   "lat": 41.72,
   "lng": 44.78,
   "currency": "GEL ~2.7/$",
   "prices": {
    "meal_cheap": 7,
    "coffee": 2,
    "beer": 2.5,
    "taxi_3km": 3,
    "transit_ride": 0.5,
    "hotel_budget": 25,
    "hotel_mid": 60,
    "hotel_lux": 150,
    "internet_month": 20,
    "sim_data": 10,
    "meal_mid_rest": 14,
    "water_bottle": 0.4,
    "daily_budget": 52,
    "daily_mid": 108
   },
   "tags": [
    "budget europe",
    "wine",
    "mountains",
    "city",
    "digital nomad"
   ],
   "best_for": [
    "sulphur baths",
    "khinkali",
    "caucasus"
   ],
   "groceries": {
    "milk_l": 1.1,
    "bread": 0.7,
    "eggs_12": 2,
    "rice_kg": 1.2,
    "chicken_kg": 3.8,
    "fruit_kg": 1.5,
    "khinkali_5": 2.8
   },
   "leisure": {
    "cinema": 6,
    "cocktail": 6,
    "gym_month": 32,
    "laundry": 2,
    "sulphur_bath": 9
   },
   "transport_extra": {
    "metro_ride": 0.35,
    "fuel_l": 1.2,
    "ridehail_km": 0.3
   },
   "activities": {
    "old_town": 0,
    "kazbegi_day": 25,
    "vineyard_tour": 40,
    "sulphur_baths": 9
   },
   "monthly": {
    "budget": 680,
    "comfortable": 1250
   },
   "seasons": "Best May-Jun, Sep-Oct. Jul-Aug hot. Winter skiing 2h away in Gudauri.",
   "airports": "TBS",
   "notes": "90-day visa-free for 90+ nationalities. Homemade wine $3-5.",
   "docs": {
    "entry": "1-year visa-free for ~90 nationalities — easiest entry in the list.",
    "insurance": "Recommended; quality private care affordable.",
    "special": [],
    "health": "None required.",
    "agency": "None needed; residencies exist for long-stayers via genuine agencies."
   }
  },
  "bestMonths": "Best May-Jun, Sep-Oct. Jul-Aug hot. Winter skiing 2h away in Gudauri.",
  "crowd": "90-day visa-free for 90+ nationalities. Homemade wine $3-5.",
  "prices": {
   "meal": 7,
   "coffee": 2,
   "taxi": 3,
   "hotel": 60
  },
  "daily_budget": 52,
  "daily_mid": 108,
  "priceLevel": "moderate",
  "best_for": [
   "sulphur baths",
   "khinkali",
   "caucasus"
  ]
 },
 "wadirum": {
  "key": "wadirum",
  "name": "Wadi Rum",
  "country": "Jordan",
  "flag": "🇯🇴",
  "lat": 29.58,
  "lng": 35.42,
  "tz": "Asia/Amman",
  "currency": "JOD (~0.71 per $1)",
  "bestView": "From a camel or 4x4 at Um Frouth rock bridge 30 minutes before sunset, when the sand goes red",
  "bestMonths": "March to May, September to November. Summer passes 40°C",
  "crowd": "Tours bunch at the big rock bridges 16:00 to 18:00. Camp overnight: after 19:00 the desert is yours",
  "kid": "Bedouin camps, camel rides, scramble-proof sand dunes, and a night sky with zero light pollution. Kids sleep in the desert.",
  "adventure": [
   "4x4 desert circuit",
   "Camel trek at dusk",
   "Bubble-dome night under the stars"
  ],
  "kidPicks": [
   "Sandboarding the red dunes",
   "Camel ride",
   "Stargazing from a Bedouin camp"
  ],
  "prices": {
   "meal": 8,
   "coffee": 1.5,
   "taxi": 6,
   "hotel": 90,
   "attraction": 20
  },
  "priceNote": "Jordan is fair value. Agree the jeep tour price BEFORE getting in; anything quoted per person over $40 is tourist-priced.",
  "kind": "featured",
  "deep": null,
  "visa": {
   "zone": "Jordan",
   "note": "Visa on arrival for most nationalities (~40 JOD); free with Jordan Pass bought before arrival.",
   "source": "https://www.jordanpass.jo/"
  },
  "daily_budget": 80,
  "daily_mid": 130,
  "priceLevel": "moderate",
  "best_for": [
   "desert camps",
   "stargazing",
   "jeep tours"
  ]
 },
 "whitehaven": {
  "key": "whitehaven",
  "name": "Hill Inlet",
  "country": "Australia (Whitsundays)",
  "flag": "🇦🇺",
  "lat": -20.28,
  "lng": 149.05,
  "tz": "Australia/Brisbane",
  "currency": "AUD (~1.5 per $1)",
  "bestView": "Hill Inlet lookout at mid-tide: the swirl is sharpest when the tide is halfway in or out, not at low tide",
  "bestMonths": "May to October: dry season, stinger-free, 24°C",
  "crowd": "Day-trip boats land 09:30 to 14:00. Sailing trips that stay past 15:00 get the beach to themselves",
  "kid": "Shallow warm lagoon water, no stingers June to July, and the purest white sand they will ever stomp in",
  "adventure": [
   "Sailing the Whitsundays",
   "Great Barrier Reef snorkel trips",
   "Sea-kayak to Langford Island"
  ],
  "kidPicks": [
   "Sand that squeaks underfoot",
   "Lookout walk (400m, pram-able)",
   "Turtle spotting from the boat"
  ],
  "prices": {
   "meal": 18,
   "coffee": 4.5,
   "taxi": 14,
   "hotel": 190,
   "attraction": 120
  },
  "priceNote": "The boat is the cost, not the beach. Compare sailing-day trips: cheap ones are day-cruises, good ones are sail.",
  "kind": "featured",
  "deep": null,
  "visa": {
   "zone": "Australia",
   "note": "Almost everyone needs an ETA or eVisitor in advance — apply online before booking flights.",
   "source": "https://immi.homeaffairs.gov.au/"
  },
  "daily_budget": 170,
  "daily_mid": 300,
  "priceLevel": "pricey",
  "best_for": [
   "white sand",
   "sailing",
   "reef swims"
  ]
 },
 "yasawa": {
  "key": "yasawa",
  "name": "Naviti Island",
  "country": "Fiji",
  "flag": "🇫🇯",
  "lat": -17.42,
  "lng": 177.19,
  "tz": "Pacific/Fiji",
  "currency": "FJD (~2.2 per $1)",
  "bestView": "The northern end of the island at low tide, when the reef flat opens a walkable path between coral gardens",
  "bestMonths": "May to October: dry, 26°C, calm water",
  "crowd": "Resort day-trips cluster at Sawa-i-Lau caves mid-morning. Island villages stay empty all day",
  "kid": "Fijians adore kids. Village visits, hermit-crab races, and water warm enough to stay in until dark",
  "adventure": [
   "Sawa-i-Lau limestone caves",
   "Reef snorkel off the resort sand",
   "Manta ray snorkel (seasonal, May-Oct)"
  ],
  "kidPicks": [
   "Hermit crab races",
   "Coral-snorkel from the beach",
   "Fijian lovo feast night"
  ],
  "prices": {
   "meal": 10,
   "coffee": 2.5,
   "taxi": 5,
   "hotel": 130,
   "attraction": 15
  },
  "priceNote": "Island resorts include meals in the rate. A kava ceremony tip is a F$5 note, not more.",
  "kind": "featured",
  "deep": null,
  "visa": {
   "zone": "Fiji",
   "note": "Visa-free entry for most Western nationals, 4 months on arrival.",
   "source": "https://www.immigration.gov.fj/"
  },
  "daily_budget": 90,
  "daily_mid": 160,
  "priceLevel": "moderate",
  "best_for": [
   "reef flats",
   "island hops",
   "cave swims"
  ]
 },
 "zanzibar-stone-town": {
  "key": "zanzibar-stone-town",
  "kind": "city",
  "name": "Zanzibar (Stone Town)",
  "city": "Zanzibar (Stone Town)",
  "country": "Tanzania",
  "flag": "🇹🇿",
  "lat": -6.16,
  "lng": 39.19,
  "tz": null,
  "currency": "TZS ~2600/$",
  "tags": [
   "islands",
   "beaches",
   "spices",
   "budget-ish",
   "tropical",
   "romantic"
  ],
  "deep": {
   "key": "zanzibar-stone-town",
   "city": "Zanzibar (Stone Town)",
   "country": "Tanzania",
   "flag": "🇹🇿",
   "lat": -6.16,
   "lng": 39.19,
   "currency": "TZS ~2600/$",
   "prices": {
    "meal_cheap": 6,
    "coffee": 2,
    "beer": 3,
    "taxi_3km": 3,
    "transit_ride": 0.5,
    "hotel_budget": 35,
    "hotel_mid": 85,
    "hotel_lux": 280,
    "internet_month": 18,
    "sim_data": 12,
    "meal_mid_rest": 16,
    "water_bottle": 0.6,
    "daily_budget": 60,
    "daily_mid": 137
   },
   "tags": [
    "islands",
    "beaches",
    "spices",
    "budget-ish",
    "tropical",
    "romantic"
   ],
   "best_for": [
    "white sand",
    "snorkeling",
    "spice tours"
   ],
   "groceries": {
    "milk_l": 1.3,
    "bread": 1,
    "eggs_12": 2.2,
    "rice_kg": 1.1,
    "chicken_kg": 3.6,
    "fruit_kg": 1.3,
    "spice_lunch": 4
   },
   "leisure": {
    "cinema": 5,
    "cocktail": 7,
    "gym_month": 35,
    "laundry": 1.4,
    "dhow_sunset": 20
   },
   "transport_extra": {
    "scooter_day": 12,
    "fuel_l": 1.2,
    "ridehail_km": 0.5
   },
   "activities": {
    "stone_town": 15,
    "spice_farm": 12,
    "snorkel": 30,
    "jozani_monkeys": 10
   },
   "monthly": {
    "budget": 800,
    "comfortable": 1500
   },
   "seasons": "Best Jun-Oct, Dec-Feb. Long rains Mar-May (many hotels close).",
   "airports": "ZNZ (or ferry)",
   "notes": "Pay extra for Azam ferries. Semi-autonomous: keep passport handy.",
   "docs": {
    "entry": "Visa on arrival or e-visa ($50) for most; mandatory travel insurance ($44) purchased from Zanzibar's official site since 2024.",
    "insurance": "ZANZIBAR-SPECIFIC mandatory insurance from official ZIC site — foreign policies don't count.",
    "special": [
     "Mandatory Zanzibar travel insurance (official portal)",
     "Yellow fever certificate if arriving from endemic country"
    ],
    "health": "Yellow fever certificate required from endemic countries; malaria prophylaxis discussed with doctor.",
    "agency": "The mandatory insurance is ONLY sold via the official ZIC portal — many fake 'insurance' sites exist."
   }
  },
  "bestMonths": "Best Jun-Oct, Dec-Feb. Long rains Mar-May (many hotels close).",
  "crowd": "Pay extra for Azam ferries. Semi-autonomous: keep passport handy.",
  "prices": {
   "meal": 6,
   "coffee": 2,
   "taxi": 3,
   "hotel": 85
  },
  "daily_budget": 60,
  "daily_mid": 137,
  "priceLevel": "pricey",
  "best_for": [
   "white sand",
   "snorkeling",
   "spice tours"
  ]
 }
};
export const KB_INDEX = [
 {
  "key": "bali-ubud",
  "kind": "city",
  "name": "Bali (Ubud)",
  "city": "Bali (Ubud)",
  "country": "Indonesia",
  "flag": "🇮🇩",
  "lat": -8.51,
  "lng": 115.26,
  "currency": "IDR ~16000/$",
  "daily_budget": 35,
  "daily_mid": 104,
  "priceLevel": "moderate",
  "best_for": [
   "wellness",
   "yoga retreats",
   "nature",
   "remote work"
  ],
  "quietPick": false,
  "tags": [
   "yoga",
   "rice terraces",
   "tropical",
   "budget",
   "wellness",
   "digital nomad",
   "waterfalls"
  ]
 },
 {
  "key": "barcelona",
  "kind": "city",
  "name": "Barcelona",
  "city": "Barcelona",
  "country": "Spain",
  "flag": "🇪🇸",
  "lat": 41.39,
  "lng": 2.17,
  "currency": "EUR ~0.92/$",
  "daily_budget": 127,
  "daily_mid": 227,
  "priceLevel": "pricey",
  "best_for": [
   "gaudi",
   "mediterranean",
   "tapas"
  ],
  "quietPick": false,
  "tags": [
   "beach",
   "architecture",
   "nightlife",
   "city",
   "foodie",
   "art"
  ]
 },
 {
  "key": "cape-town",
  "kind": "city",
  "name": "Cape Town",
  "city": "Cape Town",
  "country": "South Africa",
  "flag": "🇿🇦",
  "lat": -33.92,
  "lng": 18.42,
  "currency": "ZAR ~18/$",
  "daily_budget": 68,
  "daily_mid": 142,
  "priceLevel": "pricey",
  "best_for": [
   "table mountain",
   "penguins",
   "wine country"
  ],
  "quietPick": false,
  "tags": [
   "ocean",
   "mountains",
   "wine",
   "adventure",
   "scenic"
  ]
 },
 {
  "key": "chiang-mai",
  "kind": "city",
  "name": "Chiang Mai",
  "city": "Chiang Mai",
  "country": "Thailand",
  "flag": "🇹🇭",
  "lat": 18.79,
  "lng": 98.98,
  "currency": "THB ~35/$",
  "daily_budget": 29,
  "daily_mid": 71,
  "priceLevel": "moderate",
  "best_for": [
   "long stays",
   "cooking schools",
   "nature"
  ],
  "quietPick": false,
  "tags": [
   "mountains",
   "temples",
   "budget",
   "digital nomad",
   "calm",
   "tropical"
  ]
 },
 {
  "key": "cusco",
  "kind": "city",
  "name": "Cusco",
  "city": "Cusco",
  "country": "Peru",
  "flag": "🇵🇪",
  "lat": -13.53,
  "lng": -71.97,
  "currency": "PEN ~3.7/$",
  "daily_budget": 44,
  "daily_mid": 108,
  "priceLevel": "moderate",
  "best_for": [
   "machu picchu",
   "hiking",
   "culture"
  ],
  "quietPick": false,
  "tags": [
   "mountains",
   "inca",
   "high altitude",
   "budget",
   "adventure",
   "historic"
  ]
 },
 {
  "key": "faroe",
  "kind": "featured",
  "name": "Sørvágsvatn",
  "country": "Faroe Islands",
  "flag": "🇫🇴",
  "lat": 62.06,
  "lng": -7.35,
  "currency": "DKK (~6.9 per $1)",
  "daily_budget": 150,
  "daily_mid": 290,
  "priceLevel": "pricey",
  "best_for": [
   "cliff hikes",
   "puffins",
   "grass-roof villages"
  ],
  "quietPick": false,
  "tags": []
 },
 {
  "key": "hoi-an",
  "kind": "city",
  "name": "Hoi An",
  "city": "Hoi An",
  "country": "Vietnam",
  "flag": "🇻🇳",
  "lat": 15.88,
  "lng": 108.34,
  "currency": "VND ~25000/$",
  "daily_budget": 28,
  "daily_mid": 75,
  "priceLevel": "moderate",
  "best_for": [
   "old town",
   "cooking classes",
   "tailored clothes"
  ],
  "quietPick": false,
  "tags": [
   "lanterns",
   "budget",
   "calm",
   "beach nearby",
   "tailors",
   "foodie"
  ]
 },
 {
  "key": "iceland",
  "kind": "featured",
  "name": "Blue Lagoon",
  "country": "Iceland",
  "flag": "🇮🇸",
  "lat": 63.88,
  "lng": -22.45,
  "currency": "ISK (~140 per $1)",
  "daily_budget": 220,
  "daily_mid": 395,
  "priceLevel": "pricey",
  "best_for": [
   "northern lights",
   "lagoon soak",
   "lava fields"
  ],
  "quietPick": false,
  "tags": []
 },
 {
  "key": "kotor",
  "kind": "city",
  "name": "Kotor",
  "city": "Kotor",
  "country": "Montenegro",
  "flag": "🇲🇪",
  "lat": 42.42,
  "lng": 18.77,
  "currency": "EUR ~0.92/$",
  "daily_budget": 80,
  "daily_mid": 148,
  "priceLevel": "pricey",
  "best_for": [
   "bay of kotor",
   "old walls",
   "boat trips"
  ],
  "quietPick": false,
  "tags": [
   "fjord-like bay",
   "historic",
   "budget europe",
   "calm",
   "mountains"
  ]
 },
 {
  "key": "kyoto",
  "kind": "featured",
  "name": "Ryōan-ji",
  "city": "Kyoto",
  "country": "Japan",
  "flag": "🇯🇵",
  "lat": 35.0347,
  "lng": 135.7183,
  "currency": "JPY (~150 per $1)",
  "daily_budget": 89,
  "daily_mid": 195,
  "priceLevel": "pricey",
  "best_for": [
   "temples",
   "cherry blossom",
   "culture"
  ],
  "quietPick": false,
  "tags": [
   "zen",
   "temples",
   "tradition",
   "calm",
   "gardens",
   "city"
  ]
 },
 {
  "key": "lisbon",
  "kind": "city",
  "name": "Lisbon",
  "city": "Lisbon",
  "country": "Portugal",
  "flag": "🇵🇹",
  "lat": 38.72,
  "lng": -9.14,
  "currency": "EUR ~0.92/$",
  "daily_budget": 101,
  "daily_mid": 184,
  "priceLevel": "pricey",
  "best_for": [
   "european city break",
   "coastal walks",
   "pastries"
  ],
  "quietPick": false,
  "tags": [
   "ocean",
   "historic",
   "pastel streets",
   "foodie",
   "affordable europe",
   "city",
   "surf"
  ]
 },
 {
  "key": "lofoten",
  "kind": "featured",
  "name": "Reine",
  "country": "Norway (Lofoten)",
  "flag": "🇳🇴",
  "lat": 67.93,
  "lng": 13.09,
  "currency": "NOK (~10.5 per $1)",
  "daily_budget": 180,
  "daily_mid": 330,
  "priceLevel": "pricey",
  "best_for": [
   "midnight sun",
   "fjord hikes",
   "sea eagles"
  ],
  "quietPick": false,
  "tags": []
 },
 {
  "key": "marrakech",
  "kind": "city",
  "name": "Marrakech",
  "city": "Marrakech",
  "country": "Morocco",
  "flag": "🇲🇦",
  "lat": 31.63,
  "lng": -7.99,
  "currency": "MAD ~10/$",
  "daily_budget": 52,
  "daily_mid": 119,
  "priceLevel": "moderate",
  "best_for": [
   "medina",
   "desert trips",
   "hammams"
  ],
  "quietPick": false,
  "tags": [
   "souks",
   "desert",
   "riads",
   "budget",
   "culture",
   "warm"
  ]
 },
 {
  "key": "medellin",
  "kind": "city",
  "name": "Medellín",
  "city": "Medellín",
  "country": "Colombia",
  "flag": "🇨🇴",
  "lat": 6.24,
  "lng": -75.58,
  "currency": "COP ~4000/$",
  "daily_budget": 50,
  "daily_mid": 113,
  "priceLevel": "moderate",
  "best_for": [
   "comuna 13",
   "coffee",
   "spring weather"
  ],
  "quietPick": false,
  "tags": [
   "city",
   "eternal spring",
   "digital nomad",
   "nightlife",
   "budget-ish"
  ]
 },
 {
  "key": "mexico-city",
  "kind": "city",
  "name": "Mexico City",
  "city": "Mexico City",
  "country": "Mexico",
  "flag": "🇲🇽",
  "lat": 19.43,
  "lng": -99.13,
  "currency": "MXN ~18/$",
  "daily_budget": 64,
  "daily_mid": 146,
  "priceLevel": "pricey",
  "best_for": [
   "street tacos",
   "museums",
   "urban energy"
  ],
  "quietPick": false,
  "tags": [
   "city",
   "foodie",
   "art",
   "museums",
   "nightlife",
   "budget-ish"
  ]
 },
 {
  "key": "napali",
  "kind": "featured",
  "name": "Nāpali Coast",
  "country": "Hawaii, USA",
  "flag": "🇺🇸",
  "lat": 22.17,
  "lng": -159.6,
  "currency": "USD",
  "daily_budget": 210,
  "daily_mid": 370,
  "priceLevel": "pricey",
  "best_for": [
   "coast boat tours",
   "kalalau lookout",
   "snorkel"
  ],
  "quietPick": false,
  "tags": []
 },
 {
  "key": "pokhara",
  "kind": "city",
  "name": "Pokhara",
  "city": "Pokhara",
  "country": "Nepal",
  "flag": "🇳🇵",
  "lat": 28.21,
  "lng": 83.99,
  "currency": "NPR ~133/$",
  "daily_budget": 31,
  "daily_mid": 75,
  "priceLevel": "moderate",
  "best_for": [
   "annapurna",
   "paragliding",
   "sunrise views"
  ],
  "quietPick": false,
  "tags": [
   "mountains",
   "himalayas",
   "lakes",
   "budget",
   "adventure",
   "calm"
  ]
 },
 {
  "key": "queenstown",
  "kind": "city",
  "name": "Queenstown",
  "city": "Queenstown",
  "country": "New Zealand",
  "flag": "🇳🇿",
  "lat": -45.03,
  "lng": 168.66,
  "currency": "NZD ~0.6/$",
  "daily_budget": 140,
  "daily_mid": 258,
  "priceLevel": "pricey",
  "best_for": [
   "adrenaline capital",
   "lord of the rings",
   "alpine"
  ],
  "quietPick": false,
  "tags": [
   "adventure",
   "mountains",
   "lakes",
   "expensive",
   "bungee",
   "hiking"
  ]
 },
 {
  "key": "reykjavik",
  "kind": "city",
  "name": "Reykjavik",
  "city": "Reykjavik",
  "country": "Iceland",
  "flag": "🇮🇸",
  "lat": 64.15,
  "lng": -21.94,
  "currency": "ISK ~140/$",
  "daily_budget": 220,
  "daily_mid": 395,
  "priceLevel": "pricey",
  "best_for": [
   "northern lights",
   "blue lagoon",
   "road trips"
  ],
  "quietPick": false,
  "tags": [
   "aurora",
   "geothermal",
   "nature",
   "expensive",
   "adventure",
   "dark nights"
  ]
 },
 {
  "key": "santorini",
  "kind": "city",
  "name": "Santorini",
  "city": "Santorini",
  "country": "Greece",
  "flag": "🇬🇷",
  "lat": 36.39,
  "lng": 25.46,
  "currency": "EUR ~0.92/$",
  "daily_budget": 161,
  "daily_mid": 283,
  "priceLevel": "pricey",
  "best_for": [
   "caldera views",
   "white villages",
   "honeymoon"
  ],
  "quietPick": false,
  "tags": [
   "islands",
   "romantic",
   "views",
   "calm",
   "luxury-ish",
   "sunset"
  ]
 },
 {
  "key": "tbilisi",
  "kind": "city",
  "name": "Tbilisi",
  "city": "Tbilisi",
  "country": "Georgia",
  "flag": "🇬🇪",
  "lat": 41.72,
  "lng": 44.78,
  "currency": "GEL ~2.7/$",
  "daily_budget": 52,
  "daily_mid": 108,
  "priceLevel": "moderate",
  "best_for": [
   "sulphur baths",
   "khinkali",
   "caucasus"
  ],
  "quietPick": false,
  "tags": [
   "budget europe",
   "wine",
   "mountains",
   "city",
   "digital nomad"
  ]
 },
 {
  "key": "wadirum",
  "kind": "featured",
  "name": "Wadi Rum",
  "country": "Jordan",
  "flag": "🇯🇴",
  "lat": 29.58,
  "lng": 35.42,
  "currency": "JOD (~0.71 per $1)",
  "daily_budget": 80,
  "daily_mid": 130,
  "priceLevel": "moderate",
  "best_for": [
   "desert camps",
   "stargazing",
   "jeep tours"
  ],
  "quietPick": false,
  "tags": []
 },
 {
  "key": "whitehaven",
  "kind": "featured",
  "name": "Hill Inlet",
  "country": "Australia (Whitsundays)",
  "flag": "🇦🇺",
  "lat": -20.28,
  "lng": 149.05,
  "currency": "AUD (~1.5 per $1)",
  "daily_budget": 170,
  "daily_mid": 300,
  "priceLevel": "pricey",
  "best_for": [
   "white sand",
   "sailing",
   "reef swims"
  ],
  "quietPick": false,
  "tags": []
 },
 {
  "key": "yasawa",
  "kind": "featured",
  "name": "Naviti Island",
  "country": "Fiji",
  "flag": "🇫🇯",
  "lat": -17.42,
  "lng": 177.19,
  "currency": "FJD (~2.2 per $1)",
  "daily_budget": 90,
  "daily_mid": 160,
  "priceLevel": "moderate",
  "best_for": [
   "reef flats",
   "island hops",
   "cave swims"
  ],
  "quietPick": false,
  "tags": []
 },
 {
  "key": "zanzibar-stone-town",
  "kind": "city",
  "name": "Zanzibar (Stone Town)",
  "city": "Zanzibar (Stone Town)",
  "country": "Tanzania",
  "flag": "🇹🇿",
  "lat": -6.16,
  "lng": 39.19,
  "currency": "TZS ~2600/$",
  "daily_budget": 60,
  "daily_mid": 137,
  "priceLevel": "pricey",
  "best_for": [
   "white sand",
   "snorkeling",
   "spice tours"
  ],
  "quietPick": false,
  "tags": [
   "islands",
   "beaches",
   "spices",
   "budget-ish",
   "tropical",
   "romantic"
  ]
 }
];
// Back-compat alias: the 8 featured places, same shape as the old PLACE_DATA.
export const PLACE_DATA = Object.fromEntries(Object.entries(KB).filter(([, e]) => e.kind === "featured"));
