// scripts/kb-build.mjs — validates data/kb/*.json, regenerates index.json and
// the browser module js/kb-data.js. Run after ANY change under data/kb/.
import { readdirSync, readFileSync, writeFileSync, unlinkSync } from "node:fs";

const KB = "builds/relaxing-travel/data/kb";
const REQUIRED = ["key","kind","name","country","flag","lat","lng","tz","currency","bestMonths","crowd","prices"];

const files = readdirSync(KB).filter(f => f.endsWith(".json") && f !== "index.json");
const entries = files.map(f => JSON.parse(readFileSync(`${KB}/${f}`, "utf8")));

const seen = new Set();
for (const e of entries) {
  for (const k of REQUIRED) if (e[k] === undefined || e[k] === "") throw new Error(`${e.key}: missing ${k}`);
  if (seen.has(e.key)) throw new Error(`duplicate key ${e.key}`);
  seen.add(e.key);
}
if (entries.length < 25) throw new Error(`expected >=25 entries, got ${entries.length}`);

const sorted = [...entries].sort((a,b)=>a.key.localeCompare(b.key));
const index = sorted.map(e => ({
  key: e.key, kind: e.kind, name: e.name, city: e.city, country: e.country,
  flag: e.flag, lat: e.lat, lng: e.lng, currency: e.currency,
  daily_budget: e.daily_budget, daily_mid: e.daily_mid, tags: e.tags || [],
}));
writeFileSync(`${KB}/index.json`, JSON.stringify(index, null, 2) + "\n");

// Browser module: full KB embedded so js/ keeps synchronous imports.
const body = `// GENERATED by scripts/kb-build.mjs — do not edit. Source: data/kb/*.json
export const KB = ${JSON.stringify(Object.fromEntries(sorted.map(e => [e.key, e])), null, 1)};
export const KB_INDEX = ${JSON.stringify(index, null, 1)};
// Back-compat alias: the 8 featured places, same shape as the old PLACE_DATA.
export const PLACE_DATA = Object.fromEntries(Object.entries(KB).filter(([, e]) => e.kind === "featured"));
`;
writeFileSync("builds/relaxing-travel/js/kb-data.js", body);

// Clean up the one-time migration script.
try { unlinkSync("scripts/kb-migrate.mjs"); } catch {}
console.log(`kb-build OK: ${entries.length} entries -> index.json + js/kb-data.js`);
